-- Migration number: 0001 	 2025-06-13T09:56:38.892Z
DROP TABLE IF EXISTS ShopifySessions;

CREATE TABLE IF NOT EXISTS ShopifySessions (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    session_id VARCHAR(255) NOT NULL UNIQUE,
    shop VARCHAR(255) NOT NULL UNIQUE,
    state VARCHAR(255) NOT NULL,
    is_online BOOLEAN NOT NULL,
    access_token VARCHAR(255),
    scope TEXT,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);